### ISSUE TITLE
remote builds fail

### ISSUE THREAD

**Issue by kevinfosterNG** [kevinfosterNG/billing-outreach#1]
github actions, railways, etc. all fail to build the app that can be built successfully locally.

> `#13 0.808 npm WARN config production Use `--omit=dev` instead.
> #13 0.824
> #13 0.824 > billing-outreach@0.1.0 build
> #13 0.824 > next build
> #13 0.824
>  
> #13 1.406 warn  - You have enabled experimental feature (appDir) in next.config.js.
> #13 1.406 warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> #13 1.406
> #13 1.406 info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
>  
> #13 1.586 info  - Creating an optimized production build...
>  
> #13 16.20 info  - Compiled successfully
>  
> #13 16.21 info  - Linting and checking validity of types...
>  
> #13 18.44 Pages directory cannot be found at /app/pages or /app/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
>  
> #13 18.73 info  - Collecting page data...
>  
> #13 20.76 info  - Generating static pages (0/9)
> #13 20.83 info  - Generating static pages (2/9)
>  
> #13 20.97 info  - Generating static pages (4/9)
>  
> #13 21.05 info  - Generating static pages (6/9)
>  
> #13 30.99 TypeError: fetch failed
> #13 30.99     at Object.fetch (/app/node_modules/next/dist/compiled/undici/index.js:1:26686)
> #13 30.99     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
> #13 30.99   cause: ConnectTimeoutError: Connect Timeout Error
> #13 30.99       at onConnectTimeout (/app/node_modules/next/dist/compiled/undici/index.js:1:73055)
> #13 30.99       at /app/node_modules/next/dist/compiled/undici/index.js:1:72547
> #13 30.99       at Immediate._onImmediate (/app/node_modules/next/dist/compiled/undici/index.js:1:72937)
> #13 30.99       at processImmediate (node:internal/timers:466:21)
> #13 30.99       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
> #13 30.99     code: 'UND_ERR_CONNECT_TIMEOUT'
> #13 30.99   }
>  
> #13 30.99 }
> #13 31.01
> #13 31.01 Error occurred prerendering page "/messages". Read more: https://nextjs.org/docs/messages/prerender-error
> #13 31.01 TypeError: fetch failed
> #13 31.01     at Object.fetch (/app/node_modules/next/dist/compiled/undici/index.js:1:26686)
> #13 31.01     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>  
> #13 31.01 info  - Generating static pages (9/9)
> #13 31.01
> #13 31.01 > Export encountered errors on following paths:
> #13 31.01 	/messages/page: /messages`

**Comment by kevinfosterNG** [comment]
Azure build fail error

> Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db3bbedbc9ec29 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
> Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
> You can report issues at https://github.com/Microsoft/Oryx/issues
> 
> Oryx Version: 0.2.20230210.1, Commit: a49c8f6b8abbe95b4356552c4c884dea7fd0d86e, ReleaseTagName: 20230210.1
> 
> Build Operation ID: 87f7e294a6ae6da5
> Repository Commit : 7f3cc59489b1d575a265b3afe8b7a7597974657d
> OS Type           : bullseye
> Image Type        : githubactions
> 
> Detecting platforms...
> Detected following platforms:
>   nodejs: 18.14.0
> Version '18.14.0' of platform 'nodejs' is not installed. Generating script to install it...
> Detected the following frameworks: Next.js
> 
> Using intermediate directory '/tmp/8db3bbedbc9ec29'.
> 
> Copying files to the intermediate directory...
> Done in 1 sec(s).
> 
> Source directory     : /tmp/8db3bbedbc9ec29
> Destination directory: /home/site/wwwroot
> 
> 
> Downloading and extracting 'nodejs' version '18.14.0' to '/tmp/oryx/platforms/nodejs/18.14.0'...
> Detected image debian flavor: bullseye.
> Downloaded in 1 sec(s).
> Verifying checksum...
> Extracting contents...
> performing sha512 checksum for: nodejs...
> Done in 7 sec(s).
> 
> Removing existing manifest file
> Creating directory for command manifest file if it does not exist
> Creating a manifest file...
> Node Build Command Manifest file created.
> 
> Using Node version:
> v18.14.0
> 
> Using Npm version:
> 9.3.1
> 
> Running 'npm install'...
> 
> 
> added 287 packages, and audited 288 packages in 26s
> 
> 107 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> Running 'npm run build'...
> 
> 
> > billing-outreach@0.1.0 build
> > next build
> 
> warn  - You have enabled experimental feature (appDir) in next.config.js.
> info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
> warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> Attention: Next.js now collects completely anonymous telemetry regarding usage.
> This information is used to shape Next.js' roadmap and prioritize features.
> You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> https://nextjs.org/telemetry
> 
> info  - Creating an optimized production build...
> info  - Compiled successfully
> info  - Linting and checking validity of types...
> Pages directory cannot be found at /tmp/8db3bbedbc9ec29/pages or /tmp/8db3bbedbc9ec29/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
> info  - Collecting page data...
> info  - Generating static pages (0/9)
> info  - Generating static pages (2/9)
> info  - Generating static pages (4/9)
> info  - Generating static pages (6/9)
> SyntaxError: Unexpected token < in JSON at position 0
> info  - Generating static pages (9/9)
>     at JSON.parse (<anonymous>)
>     at packageData (node:internal/deps/undici/undici:6403:23)
>     at specConsumeBody (node:internal/deps/undici/undici:6381:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async getMessages (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:421:22)
>     at async MessagesPage (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:431:22)
> 
> Error occurred prerendering page "/messages". Read more: https://nextjs.org/docs/messages/prerender-error
> SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at packageData (node:internal/deps/undici/undici:6403:23)
>     at specConsumeBody (node:internal/deps/undici/undici:6381:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async getMessages (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:421:22)
>     at async MessagesPage (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:431:22)
> 
> > Export encountered errors on following paths:
> 	/messages/page: /messages
> warn  - You have enabled experimental feature (appDir) in next.config.js.\nwarn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.\n\nPages directory cannot be found at /tmp/8db3bbedbc9ec29/pages or /tmp/8db3bbedbc9ec29/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.\nSyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at packageData (node:internal/deps/undici/undici:6403:23)\n    at specConsumeBody (node:internal/deps/undici/undici:6381:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getMessages (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:421:22)\n    at async MessagesPage (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:431:22)\n\nError occurred prerendering page "/messages". Read more: https://nextjs.org/docs/messages/prerender-error\nSyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at packageData (node:internal/deps/undici/undici:6403:23)\n    at specConsumeBody (node:internal/deps/undici/undici:6381:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getMessages (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:421:22)\n    at async MessagesPage (/tmp/8db3bbedbc9ec29/.next/server/app/messages/page.js:431:22)\n\n> Export encountered errors on following paths:\n	/messages/page: /messages\n/bin/bash -c "oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db3bbedbc9ec29 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
